export let products = [
    {
        id: 1,
        title: "Libreta Margarita",
        price: 12.95,
        stock: 100,
        description: "¡Agrega un toque de elegancia y estilo a tus notas y apuntes con nuestra hermosa Libreta Margarita! Diseñada para cautivar, esta libreta combina funcionalidad y belleza en un solo objeto. Con su portada adornada con un estampado de margaritas en tonos pasteles y alegres, esta libreta se convierte en un accesorio irresistible para cualquier amante de la papelería bonita. Ya sea que necesites una libreta para tomar notas, hacer bocetos o mantener tus pensamientos organizados, nuestra Libreta Margarita es una opción perfecta.",
        category: "flores",
        img: "https://res.cloudinary.com/djmvj6dpt/image/upload/v1689063769/ecommerce-libretasbonitas/libreta-margarita.jpg",
    },
    {
        id: 2,
        title: "Libreta Rosa",
        price: 12.95,
        stock: 100,
        description: "Sumérgete en un mundo de dulzura y feminidad con nuestra encantadora Libreta Rosa. Esta libreta es la combinación perfecta entre estilo y funcionalidad, diseñada para añadir un toque de elegancia a tus momentos de escritura. Con su suave y delicada portada rosa, esta libreta captura la esencia de la feminidad y transmite una sensación de calma y serenidad.Ya sea que la utilices para tomar notas, hacer listas o expresar tus pensamientos creativos, esta libreta se convertirá en tu compañera perfecta. Su tamaño compacto la hace ideal para llevarla contigo a todas partes, para que nunca pierdas la oportunidad de capturar tus ideas en el momento exacto en que surgen.",
        category: "flores",
        img: "https://res.cloudinary.com/djmvj6dpt/image/upload/v1689063769/ecommerce-libretasbonitas/libreta-rosa.jpg",
    },
    {
        id: 3,
        title: "Libreta Panda",
        price: 12.95,
        stock: 100,
        description: "¡Agrega un toque de diversión y positividad a tus días con nuestra adorable Libreta Panda! Déjate cautivar por la ternura de este pequeño panda, que te recordará constantemente que eres especial y capaz de lograr grandes cosas. Su diseño alegre y optimista te llenará de energía y motivación cada vez que abras esta libreta. Deja que este adorable panda se convierta en tu compañero diario mientras conquistas el mundo con tus ideas y logros.",
        category: "animales",
        img: "https://res.cloudinary.com/djmvj6dpt/image/upload/v1689063769/ecommerce-libretasbonitas/libreta-panda.jpg",
    },
    {
        id: 4,
        title: "Libreta Llama",
        price: 12.95,
        stock: 100,
        description: "¡Deja que la divertida y encantadora Libreta Llama ilumine tus días con su estilo único y su actitud positiva! La portada de esta libreta presenta un diseño colorido y adorable con una llama simpática y juguetona. Esta libreta se convierte en un recordatorio constante de que no importa cuáles sean los desafíos que enfrentes, puedes superarlos con una actitud positiva y una sonrisa en tu rostro. Ya sea que la lleves contigo a la escuela, al trabajo o la tengas en tu escritorio en casa, la Libreta Llama se convertirá en un compañero alegre y motivador. Te animará a enfrentar cada día con una mentalidad positiva y te recordará que no hay problema demasiado grande para resolver.",
        category: "animales",
        img: "https://res.cloudinary.com/djmvj6dpt/image/upload/v1689063769/ecommerce-libretasbonitas/libreta-llama.jpg",
    },
    {
        id: 5,
        title: "Libreta Cerezas",
        price: 12.95,
        stock: 100,
        description: "Sumérgete en un mundo de dulzura y encanto con nuestra cautivadora Libreta Cerezas. Diseñada para despertar tus sentidos y despertar tu creatividad, esta libreta es el complemento perfecto para aquellos que buscan una experiencia de escritura única. La portada de la libreta está adornada con una ilustración vibrante y detallada de cerezas jugosas y tentadoras, que te invitan a explorar un universo de ideas frescas y pensamientos creativos. Con cada página que volteas, te sumergirás en un maravilloso viaje de inspiración. Ya sea que la utilices para anotar tus metas, dibujar bocetos o capturar momentos de inspiración, la Libreta Cerezas te acompañará en cada paso de tu viaje creativo.",
        category: "aesthetics",
        img: "https://res.cloudinary.com/djmvj6dpt/image/upload/v1689063769/ecommerce-libretasbonitas/libreta-cerezas.jpg",
    },
    {
        id: 6,
        title: "Libreta Dreams",
        price: 12.95,
        stock: 100,
        description: "Deja que nuestra maravillosa Libreta Dreams sea tu compañera en el viaje hacia la realización de tus sueños. Con su inspiradora frase Dreams do come true en la portada, esta libreta está diseñada para recordarte constantemente que tus sueños pueden hacerse realidad. Cada vez que abras esta libreta, te sumergirás en un mundo de posibilidades y te sentirás inspirado para perseguir tus sueños más preciados. La Libreta Dreams es mucho más que un simple cuaderno: es un recordatorio constante de que puedes lograr todo aquello que te propongas. Lleva esta libreta contigo en tu día a día, ya sea en el trabajo, en la escuela o en tus momentos de reflexión personal, y conviértela en tu confidente para explorar tus pensamientos y convertirlos en realidad.",
        category: "aesthetics",
        img: "https://res.cloudinary.com/djmvj6dpt/image/upload/v1689063769/ecommerce-libretasbonitas/libreta-dreams.jpg",
    },
]